### ISSUE TITLE
don't specify loginverify  failed redirect external url

### ISSUE THREAD

**Issue by pragnesh9199** [pyepye/django-magiclink#10]
you have already define login failed overide template name variable,
MAGICLINK_LOGIN_FAILED_TEMPLATE_NAME = 'magiclink/login_failed.html' 
but i want direct redirect frontend url so please find any solution and add  MAGICLINK_LOGIN_FAILED_URL 

i have find one solution
**add settings.py in overide variable MAGICLINK_LOGIN_FAILED_TEMPLATE_NAME =  False**
**MAGICLINK_LOGIN_FAILED_URL = "your login failed url"**
@method_decorator(never_cache, name='dispatch')
class LoginVerify(TemplateView):
    template_name = settings.LOGIN_FAILED_TEMPLATE_NAME

    def get(self, request, *args, **kwargs):
        token = request.GET.get('token')
        email = request.GET.get('email')
        user = authenticate(request, token=token, email=email)
        if not user:
            if settings.LOGIN_FAILED_TEMPLATE_NAME:
                context = self.get_context_data(**kwargs)
                # The below settings are left in for backward compatibility
                context['ONE_TOKEN_PER_USER'] = settings.ONE_TOKEN_PER_USER
                context['REQUIRE_SAME_BROWSER'] = settings.REQUIRE_SAME_BROWSER
                context['REQUIRE_SAME_IP'] = settings.REQUIRE_SAME_IP
                context['ALLOW_SUPERUSER_LOGIN'] = settings.ALLOW_SUPERUSER_LOGIN  # NOQA: E501
                context['ALLOW_STAFF_LOGIN'] = settings.ALLOW_STAFF_LOGIN

                try:
                    magiclink = MagicLink.objects.get(token=token)
                except MagicLink.DoesNotExist:
                    error = 'A magic link with that token could not be found'
                    context['login_error'] = error
                    return self.render_to_response(context)

                try:
                    magiclink.validate(request, email)
                except MagicLinkError as error:
                    context['login_error'] = str(error)

                return self.render_to_response(context)
            else:
                **return HttpResponseRedirect(settings.MAGICLINK_LOGIN_FAILED_URL)**

        login(request, user)
        log.info(f'Login successful for {email}')

        magiclink = MagicLink.objects.get(token=token)
        response = HttpResponseRedirect(magiclink.redirect_url)
        if settings.REQUIRE_SAME_BROWSER:
            cookie_name = f'magiclink{magiclink.pk}'
            response.delete_cookie(cookie_name, magiclink.cookie_value)
        return response

**add line return HttpResponseRedirect(settings.MAGICLINK_LOGIN_FAILED_URL) and remove raise Http404()**

**Comment by pyepye** [comment]
Hi @pragnesh9199  

While using a redirect URL means you lose the reason the login failed, it does seem like an easy way to make the app more front-end friendly which is a good thing.

I've made a version of your suggested change - https://github.com/pyepye/django-magiclink/commit/319df007c40650f35ff9b0c4549f67b5b831d3f0

I've created a new release - version [1.1.0](https://github.com/pyepye/django-magiclink/releases/tag/1.1.0) - which has been pushed to Pypi.

Thanks
Matt

**Comment by pragnesh9199** [comment]
Thanks

**Comment by pragnesh9199** [comment]
Thanks
