### ISSUE TITLE
Anonimize/not store IP addresses

### ISSUE THREAD

**Issue by efojs** [pyepye/django-magiclink#8]
We can't afford keeping IP address, at least not anonymized ones
And I cant' find a way to customize this, because you save it in `create_magiclink()` helper

Could you please add some solution?
Either not store them at all, if `MAGICLINK_REQUIRE_SAME_IP` is set to `False`
Or at least anonymize it by default or by option (by removing last part for IP4? not sure about IP6)

**Comment by efojs** [comment]
Also are magiclinks intended to be stored permanently? What is it for? Or did make something wrong?

**Comment by pyepye** [comment]
Hey @efojs 

Very good point with the IP addresses. I'll look at not storing them when `MAGICLINK_REQUIRE_SAME_IP` is false as well as adding a note about them being stored. 
I also like the idea of anonymising the IP by default as well. It would make the `REQUIRE_SAME_IP` a tiny bit more insecure but I think it's worth it. I'll add a `MAGICLINK_ANONYMIZE_IP` setting which is turned on by default.

As for the magic links being stored permanently. This is something I thought about when first creating the plugin.  Whether to soft delete (disable) or hard delete. I decided not destroying data and being able to show the `Magic link has been used too many times` and `Magic link has expired` errors were helpful. 

If you are using any kind of background / periodic tasks via celery etc I would advise a cleanup via that. It would probably be good to add in a similar management command to Django's `clearsessions` though so it's easy to clean up via a cron or something. I'll look into that as well.

**Comment by efojs** [comment]
Hi! Any progress with this feature?  
Maybe you have some suggestion for monkey-patching it?  
Like can I piggyback on some signal and just delete this value?

**Comment by efojs** [comment]
Oh, I forgot and then overlooked "management command to Django's `clearsessions`" — yes, I'll try it. We don't use Celery on this project, but maybe `cron` will work well. So just removing IPs of expired links looks to be enough this way.

**Comment by pyepye** [comment]
Hi @efojs 

Very late but I've finally found an evening to work on these bits:

* The IP addresses are now anonymized by default be replacing the last octet with a 0 - https://github.com/pyepye/django-magiclink/commit/a659d68a3c1531c98283e979074dcf1516e8c431
* The IP address are only stored if REQUIRE_SAME_IP is set - https://github.com/pyepye/django-magiclink/commit/7508d48e08bf2234268e92797856eaf82997cf63
* There is now a management command to remove old expired magic links - https://github.com/pyepye/django-magiclink/commit/c809859e531aa99eddd859681330ce0fff2891f6

I've just doing a few other fixes, I'll create a new version and release it to Pypi later.


Thanks
Matt

**Comment by pyepye** [comment]
I've created a new release - version [1.1.0](https://github.com/pyepye/django-magiclink/releases/tag/1.1.0) - which has been pushed to Pypi
